### ISSUE TITLE
Image Scaling Feture

### ISSUE THREAD

**Issue by furkankurt** [denzcoskun/ImageSlideshow#10]
Hi, thank you so much for this library. I want to scale the imageview.
How can I do? Can you add a feture?

**Comment by xbahaa** [comment]
i have the same problem here where is this guy

**Comment by denzcoskun** [comment]
Hi, you can with new version.

`implementation 'com.github.denzcoskun:ImageSlideshow:0.0.7'`

Please read the readme before use. Scale types changed.
