### ISSUE TITLE
Stop Image Auto Scaling

### ISSUE THREAD

**Issue by mehul0** [denzcoskun/ImageSlideshow#11]
Hello, Thanks for the wonderful library. 
I used this library for image slider and for product detail, this library perfectly feet for image slider in my case. however, I want to stop image auto-scaling on product view. how can I fix this? Thanks.

**Comment by denzcoskun** [comment]
Hello, thanks for good comments. 

If I remove auto scalling, image cant look fit.

I'm trying for scaling problems but Picasso can't add every scale type. I added centerCrop scaleType and I will add centerInside scaleType  to next update.

Do you have any idea?

**Comment by mehul0** [comment]
Thanks, @denzcoskun for the fast reply.

Is it possible to add an option for remove auto-scaling like you did in your last update for centerCrop. and for all scale type, you may look into the Glide.

**Comment by denzcoskun** [comment]
Hi, you can with new version.

implementation 'com.github.denzcoskun:ImageSlideshow:0.0.7'

Please read the readme before use. Scale types changed.
