### ISSUE TITLE
AutoSlide control from code

### ISSUE THREAD

**Issue by ntorres144** [denzcoskun/ImageSlideshow#12]
Hi, thanks for this library, easy to use and the default options work great for many cases.

I have a an issue, i need a way to Start/stop the autoslide function but there is no func for that in your code, also a way to modify the period time of the autoslide.

Also without this function I give this lib a Star, great work.

**Comment by denzcoskun** [comment]
You can use now with new version.
```kt
imageSlider.startSliding(3000) // with new period
imageSlider.startSliding()
imageSlider.stopSliding()
```
```kt
implementation 'com.github.denzcoskun:ImageSlideshow:0.0.6'
```

**Comment by ntorres144** [comment]
Hey!, thanks! will try it now

**Comment by MrVipinVijayan** [comment]
imageSlider.startSliding(3000)
is not working. it takes the default value from the XML set in layout.
