### ISSUE TITLE
setItemClickListener not working

### ISSUE THREAD

**Issue by moeindev** [denzcoskun/ImageSlideshow#20]
Hello! Thanks for this amazing lib,

I tried to add item click listener but it is not working!

```
binding.homeSlider.setItemClickListener(object : ItemClickListener {
            override fun onItemSelected(position: Int) {
                Log.i("slider","item selected $position")
                Log.d("slider","slider value is null!")
                vm.slider.value?.let {
                    val slider = it[position]

                    if (slider.category != "0"){
                        val products = homeToProducts(slider.category)
                        view?.let {
                            findNavController(it).navigate(products)
                        }
                    }
                    if (slider.sliderURL != "") {
                        val i = Intent(Intent.ACTION_VIEW)
                        i.data = Uri.parse(slider.sliderURL)
                        startActivity(i)
                    }
                }
            }
        } )
```

**Comment by moeindev** [comment]
Yeah still not working, 
I put this log to monitor the listener: 
```
Log.i("slider","item selected $position")
```
But it doesn't show the log!

I use databinding and testing device is operating android 10

**Comment by Janindu077** [comment]
Yeah, still not working. 
I tried in java.  setItemClickListener not working  
but setItemChangeListener Working.
why it's?
` this.imageSlider.setItemChangeListener(new ItemChangeListener() {
            @Override
            public void onItemChanged(int i) {
                Log.d(TAG, "pos :" + i);
// working
            }
        });`
`
        this.imageSlider.setItemClickListener(new ItemClickListener() {
            @Override
            public void onItemSelected(int i) {
                Log.d(TAG, "Selected item " + i);
            }
        });`

**Comment by denzcoskun** [comment]
Hello,
I tried click listener, its working with my code. Can you check this sample?
```Java
imageSlider.setItemClickListener(new ItemClickListener() {
            @Override
            public void onItemSelected(int position) {
                // You can listen here.
                System.out.println("POS Kotlin: " + position);
            }
        });
```

**Comment by bleedweedsuz** [comment]
I had the same problem it took me hour to figure it out. Solution is bind data first and use clicklistener after.
Example:

```
//Bind Data First
imageSlider.setImageList(slide_list, true); //here slide_list is array list of SlideModel() object

//Bind Listener
imageSlider.setImageClickListener( i -> {
   System.out.println("Clicked on " + i);
});

```

**Comment by Takshbeladiya** [comment]
Got similar problem Solution :- Step 1 :- bind data first Step 2 :-  Use click event after binding.

// java Code binding data from Firebase

        FirebaseDatabase.getInstance().getReference().child("Slider")
                .addListenerForSingleValueEvent(new ValueEventListener() {
                    @Override
                    public void onDataChange(@NonNull DataSnapshot snapshot) {
                        // this loop will take all children from database itinerary
                        for(DataSnapshot data:snapshot.getChildren()){

                            // First Bind Data
                            remote_image.add(new SlideModel(data.child("url").getValue().toString(),
                                    data.child("title").getValue().toString(),
                                    ScaleTypes.FIT
                            ));
                        }
                        main_slider.setImageList(remote_image, ScaleTypes.FIT);

                        // Now Use Click Event
                        main_slider.setItemClickListener(new ItemClickListener() {
                            @Override
                            public void onItemSelected(int i) {
                                Toast.makeText(referenceActivity, "item selected", Toast.LENGTH_SHORT).show();
                            }

                            @Override
                            public void doubleClick(int i) {
                                Toast.makeText(referenceActivity, "double clicked", Toast.LENGTH_SHORT).show();
                            }
                        });
                    }

                    @Override
                    public void onCancelled(@NonNull DatabaseError error) {
                        // Leave empty
                    }
                }
