### ISSUE TITLE
error: duplicate value for resource 'attr/corner_radius' with config ''.

### ISSUE THREAD

**Issue by luhemusa** [denzcoskun/ImageSlideshow#21]
Hi, 

I have this problem when i try run the application. what can i do ? 

jetified-ImageSlideshow-0.0.6\res\values\values.xml:3:5-12:25: AAPT: error: duplicate value for resource 'attr/corner_radius' with config ''.

**Comment by denzcoskun** [comment]
Can you share your xml code?

**Comment by luhemusa** [comment]
> Can you share your xml code?

<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/mdtp_white">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <androidx.core.widget.NestedScrollView

            android:id="@+id/nested_content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:scrollbars="none"
            android:fillViewport="true"
            >

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="center_horizontal"
                android:orientation="vertical"
                >

                <androidx.cardview.widget.CardView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/spacing_large"
                    android:layout_marginRight="@dimen/spacing_large"
                    android:layout_marginTop="@dimen/spacing_middle"
                    android:background="@android:color/white"
                    app:cardCornerRadius="5dp"
                    app:cardElevation="2dp"
                    app:cardUseCompatPadding="true"
                    >

                    <com.denzcoskun.imageslider.ImageSlider
                    android:layout_width="match_parent"
                    app:auto_cycle="true"
                    app:delay="0"
                    android:id="@+id/slider"
                    app:period="1000"
                    app:error_image="@drawable/bg_grey"
                    app:placeholder="@drawable/bg_grey"
                    app:corner_radius="20"
                    android:layout_height="200dp"/>


                </androidx.cardview.widget.CardView>
</LinearLayout>

        </androidx.core.widget.NestedScrollView>
    </LinearLayout>

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by luhemusa** [comment]
> Can you share your xml code?

Sure there is my XML Complete.



<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/mdtp_white">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <androidx.core.widget.NestedScrollView

            android:id="@+id/nested_content"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:scrollbars="none"
            android:fillViewport="true"
            >

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="center_horizontal"
                android:orientation="vertical"
                >

                <androidx.cardview.widget.CardView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/spacing_large"
                    android:layout_marginRight="@dimen/spacing_large"
                    android:layout_marginTop="@dimen/spacing_middle"
                    android:background="@android:color/white"
                    app:cardCornerRadius="5dp"
                    app:cardElevation="2dp"
                    app:cardUseCompatPadding="true"
                    >

                    <com.denzcoskun.imageslider.ImageSlider
                    android:layout_width="match_parent"
                    app:auto_cycle="true"
                    app:delay="0"
                    android:id="@+id/slider"
                    app:period="1000"
                    app:error_image="@drawable/bg_grey"
                    app:placeholder="@drawable/bg_grey"
                    app:corner_radius="20"
                    android:layout_height="200dp"/>


                </androidx.cardview.widget.CardView>

                <androidx.cardview.widget.CardView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/spacing_large"
                    android:layout_marginRight="@dimen/spacing_large"
                    android:layout_marginTop="@dimen/spacing_middle"
                    android:background="@android:color/white"
                    app:cardCornerRadius="2dp"
                    app:cardElevation="2dp"
                    app:cardUseCompatPadding="true">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="vertical"
                        android:padding="@dimen/spacing_large">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="Categorias"
                            android:textAppearance="@style/TextAppearance.AppCompat.Medium"
                            android:textColor="@color/grey_90" />

                        <androidx.recyclerview.widget.RecyclerView
                            android:id="@+id/recycler_categorias_home"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"/>

                    </LinearLayout>

                </androidx.cardview.widget.CardView>

                <androidx.cardview.widget.CardView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/spacing_large"
                    android:layout_marginRight="@dimen/spacing_large"
                    android:layout_marginTop="@dimen/spacing_middle"
                    android:background="@android:color/white"
                    app:cardCornerRadius="2dp"
                    app:cardElevation="2dp"
                    app:cardUseCompatPadding="true">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="vertical"
                        android:padding="@dimen/spacing_large">

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:text="Pedidos Recientes"
                            android:textAppearance="@style/TextAppearance.AppCompat.Medium"
                            android:textColor="@color/grey_90" />

                        <androidx.recyclerview.widget.RecyclerView
                            android:id="@+id/recycler_pedidos_recientes_home"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"/>


                    </LinearLayout>

                </androidx.cardview.widget.CardView>

                <View
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/spacing_large" />

                <Button
                    android:id="@+id/cerrar_session"
                    android:layout_width="300dp"
                    android:layout_height="wrap_content"
                    android:background="@color/red_800"
                    android:text="Cerrar Sesion"
                    android:textColor="#FAF5F5" />
                <View
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/spacing_large" />

            </LinearLayout>

        </androidx.core.widget.NestedScrollView>
    </LinearLayout>

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by denzcoskun** [comment]
Is **@drawable/bg_grey** image or xml? You can use xml but this attribute just support image now.

I created a new project. I added project gradle.
allprojects {
    repositories {
        ...
        **maven { url 'https://jitpack.io' }**
    }
}
and I added module gradle 
**implementation 'com.github.denzcoskun:ImageSlideshow:0.0.6'**

so it was run now.

![Screenshot_1588262300](https://user-images.githubusercontent.com/15522554/80732606-3cde5800-8b15-11ea-8f26-c2b583d16318.png)

**Comment by luhemusa** [comment]
Ok now when i try to Sync the library on Dependencies i already have the problem ,

i use (implementation 'com.github.denzcoskun:ImageSlideshow:0.0.6')

and the error shows me this ..

![image](https://user-images.githubusercontent.com/64600793/80734415-701de880-8b0f-11ea-8df4-1f9e43ebdf86.png)

**Comment by luhemusa** [comment]
this is my gradle app 

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "com.example.appdelivery"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.firebase:firebase-auth:16.0.5'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.android.support:multidex:1.0.3'
    //----------------------------------------------------------------------------------------------

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'

    // google maps library ------------------------------------------------------------------------
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation('com.google.android.libraries.places:places:1.0.0') {
        exclude module: 'glide'
    }

    // google gson --------------------------------------------------------------------------------
    implementation 'com.google.code.gson:gson:2.8.4'

    // third party dependencies -------------------------------------------------------------------
    implementation 'com.balysv:material-ripple:1.0.2'                  // ripple effect
    implementation 'com.github.bumptech.glide:glide:3.7.0'             // image loader
    implementation 'com.wdullaer:materialdatetimepicker:3.2.0'         // date & time picker
    implementation 'com.mikhaellopez:circularimageview:3.2.0'          // circle image view

    implementation 'com.hootsuite.android:nachos:1.1.1'                // material chips
    implementation 'com.google.android:flexbox:0.3.2'                  // google flexible box
    implementation 'com.crystal:crystalrangeseekbar:1.1.3'             // range seek bar

    //VOLLEY****************************************************************************************
    implementation 'com.android.volley:volley:1.1.0'

    //AUTENTICACION------------------------------------------------------------------------------------------
    implementation 'com.google.android.gms:play-services-auth:18.0.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:17.4.0'
    implementation 'com.google.firebase:firebase-auth:19.1.0'
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    //MAPA--------------------------------------------------------
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.google.android.libraries.places:places:2.2.0'
    implementation 'com.google.android.gms:play-services-places:16.0.0'
    implementation 'com.airbnb.android:lottie:2.8.0'

    //lottie-----------------------------------------------------
    implementation 'com.airbnb.android:lottie:3.4.0'

    //slider-----------------------------------------------------
    implementation 'com.loopj.android:android-async-http:1.4.9'
    implementation 'com.github.JakeWharton:ViewPagerIndicator:2.4.1'
    implementation 'com.github.denzcoskun:ImageSlideshow:0.0.6'
}

**Comment by luhemusa** [comment]
and my Gradle Project

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.1'
        classpath 'com.google.gms:google-services:4.3.3'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by denzcoskun** [comment]
I tried your all dependencies implementations and I found your problem.

**CrystalRangeSeekbar** and **ImageSliderShow** use same **corner_radius** variable. This application try to merge all attribute but same names throw error.

To sum up, you cant use this libraries same time now. I added to my notes, I can fix on next version.

**Comment by luhemusa** [comment]
I understand, thank you very much for your help. For the moment I will try to stop using the other library. again thank you very much excellent attention
