### ISSUE TITLE
ImageTitle

### ISSUE THREAD

**Issue by Eslamyounis34** [denzcoskun/ImageSlideshow#28]
can i center the title inside image ?

**Comment by denzcoskun** [comment]
Yes, but you must implement new version and you must update your project new options.

`
implementation 'com.github.denzcoskun:ImageSlideshow:0.0.7'
`
Also

```
<com.denzcoskun.imageslider.ImageSlider
        android:id="@+id/image_slider"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        app:iss_auto_cycle="true"
        app:iss_period="1000"
        app:iss_delay="0"/>
```

You should add elements have **iss_** code before attiribute. **app:iss_period="1000"** like it.

`
app:iss_text_align="CENTER"
`

And you can use.
