### ISSUE TITLE
 'META-INF/imageslider_release.kotlin_module'.

### ISSUE THREAD

**Issue by noaman813** [denzcoskun/ImageSlideshow#30]
hi, I get this error
More than one file was found with OS independent path 'META-INF/imageslider_release.kotlin_module'.

**Comment by denzcoskun** [comment]
**Can you check this page:** https://stackoverflow.com/questions/44342455/more-than-one-file-was-found-with-os-independent-path-meta-inf-license

**Comment by noaman813** [comment]
I've try it but the error doesn't resolved

**Comment by denzcoskun** [comment]
Did you try it? https://stackoverflow.com/a/53165350
