### ISSUE TITLE
Title and Image

### ISSUE THREAD

**Issue by Emusko** [denzcoskun/ImageSlideshow#31]
Hello kardes, I want to delete title from the image and save only slides. How can I achieve that? Memnun olurum yardimci olursan

**Comment by denzcoskun** [comment]
Hello, title is not required. You can use without title.

```kt
imageList.add(SlideModel("String Url" or R.drawable)

imageList.add(SlideModel("String Url" or R.drawable, "title") // with title
```

**Comment by Emusko** [comment]
Thank you, works like a charm!
