### ISSUE TITLE
Indicator Position change

### ISSUE THREAD

**Issue by Kinjal62** [denzcoskun/ImageSlideshow#34]
Thanks for this library. It works well. but I'm facing one problem I want to change the indicator gravity center to left. Is it possible when I use this library? Or else can I use custom or another library for the indicator only?

**Comment by denzcoskun** [comment]
Hello, it is not possible yet. It can be add as a feature. I added in my notes and I will add with new version.

**Comment by chinnaharsha09** [comment]
When can expect this feature?

Thanks in advance. :-)

**Comment by denzcoskun** [comment]
Hello,

You can add **app:iss_indicator_align** with new version.

```xml
<com.denzcoskun.imageslider.ImageSlider
        android:id="@+id/image_slider"
        android:layout_width="match_parent"
        android:layout_height="300dp"
        app:iss_auto_cycle="true"
        app:iss_period="1000"
        app:iss_indicator_align="LEFT"
        app:iss_delay="0"/>
```
`
implementation 'com.github.denzcoskun:ImageSlideshow:0.1.0'
`

![image](https://user-images.githubusercontent.com/15522554/97341877-a8bc3600-1896-11eb-9647-101dbc2ea3d1.png)

**Comment by Kinjal62** [comment]
> Hello,
> 
> You can add **app:iss_indicator_align** with new version.
> 
> ```
> <com.denzcoskun.imageslider.ImageSlider
>         android:id="@+id/image_slider"
>         android:layout_width="match_parent"
>         android:layout_height="300dp"
>         app:iss_auto_cycle="true"
>         app:iss_period="1000"
>         app:iss_indicator_align="LEFT"
>         app:iss_delay="0"/>
> ```
> 
> `implementation 'com.github.denzcoskun:ImageSlideshow:0.1.0'`
> 
> ![image](https://user-images.githubusercontent.com/15522554/97341877-a8bc3600-1896-11eb-9647-101dbc2ea3d1.png)

Thanks a lot for this.
