### ISSUE TITLE
not removed old list (multiple images -> single image) 

### ISSUE THREAD

**Issue by theeeeeee** [denzcoskun/ImageSlideshow#40]
Hi
I have a problem with setting images in ImageSlider

when I set the new image list(single image) into the ImageSlider object that already has image list(multiple images), old list is still remained
And also indicator dots are remained too

my code just do when images are changed, create new array and add image URLs and set into the ImageSlider object
Am I have to clear the ImageSlider's image list?

I saw closed issue similar with me... but I think it's not fixed completely.. or my fault

**Comment by denzcoskun** [comment]
Hello,

I found an error and fixed in new version. 

You can try with new version

```
implementation 'com.github.denzcoskun:ImageSlideshow:0.1.0'
```

**Comment by theeeeeee** [comment]
Thanks for answer!
it works good!
