### ISSUE TITLE
problem with setItemClickListener

### ISSUE THREAD

**Issue by singhal-ekansh** [denzcoskun/ImageSlideshow#43]
clicks not working in new version

**Comment by denzcoskun** [comment]
Hello, I tried it and it works on my project. Can you examine these examples?
**Kotlin**
```Kotlin
imageSlider.setItemClickListener(object : ItemClickListener {
            override fun onItemSelected(position: Int) {
                // You can listen here.
                println("POS Kotlin: " + position)
            }
        })
```
![image](https://user-images.githubusercontent.com/15522554/99800958-46c5b800-2b46-11eb-8f65-23f22481d1c0.png)

**Java**
```Java
imageSlider.setItemClickListener(new ItemClickListener() {
            @Override
            public void onItemSelected(int position) {
                // You can listen here.
                System.out.println("POS Java: " + position);
            }
        });
```
![image](https://user-images.githubusercontent.com/15522554/99800813-05cda380-2b46-11eb-8d0d-5dc64b5b23e3.png)

**Comment by singhal-ekansh** [comment]
sorry for the inconvenience. Its working.
