### ISSUE TITLE
Cannot resolve constructor 'SlideModel(java.lang.String)'

### ISSUE THREAD

**Issue by alativity** [denzcoskun/ImageSlideshow#45]
Hello, today I updated to version 0.1.0 of the library and ran into a problem that this code stopped working for me. I work in Java, and the shown example on Kotlin worked for me, but alas, nothing in Java.

I would really thank you for your help, thank you.

`List<SlideModel> slideModels = new ArrayList<>();

        for (String s : sub_uris_list) {
            slideModels.add(new SlideModel(s));
        }

        imageSlider.setImageList(slideModels, ScaleTypes.FIT);`

**Comment by denzcoskun** [comment]
Hello, I added my notes. I will fix with next version. Can you use with ScaleTypes?

```Java
for (String s : images) {
      imageList.add(new SlideModel(s, ScaleTypes.FIT));
}
```

**Comment by alativity** [comment]
Yes, of course, thank you for your prompt reply.
This worked for me.
