### ISSUE TITLE
Title text align

### ISSUE THREAD

**Issue by rezaasdin** [denzcoskun/ImageSlideshow#52]
Hi 
How can I use title align?
center value for `app:iss_text_align` doesn't works for me

**Comment by Shvet** [comment]
how are you setting text aligne? You need to put either `START`, `END` or `CENTER` into it.

**Comment by RayNjire** [comment]
> how are you setting text aligne? You need to put either `START`, `END` or `CENTER` into it.

This was a good hint on how to use app: iss_text_align, but it doesn't work on the title of the images.  Please help if you can. I would like the title of each image to be to the right/end

**Comment by denzcoskun** [comment]
LEFT, RIGHT or CENTER
