### ISSUE TITLE
How to change color of title 

### ISSUE THREAD

**Issue by punjan** [denzcoskun/ImageSlideshow#69]
I want to change the color of the title, how do I do that? Thanks.

**Comment by BaronCandy** [comment]
hello idk if u still need but make a resource file named gradient and give it specs u want `<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape>
            <gradient
                android:angle="90"
                android:startColor="@color/purple_700"
                android:endColor="@color/purple_200"
                android:type="linear"

                />
        </shape>
    </item>

</selector>
`
and colour to whatever u like

**Comment by denzcoskun** [comment]
You can change with new version(0.1.2).

app:iss_text_color="#FFA0A0"

Also new animations added. You can try them.
