### ISSUE TITLE
Set in java

### ISSUE THREAD

**Issue by Aptul9** [denzcoskun/ImageSlideshow#7]
Hi, I have tried to set the slider in java instead of kotlin, but somehow it keeps crashing, is there a way to set it?

**Comment by denzcoskun** [comment]
You can use it with Java code similar to Kotlin code.
```Java
ImageSlider imageSlider = (ImageSlider) findViewById(R.id.image_slider);

List <SlideModel> imageList = new ArrayList<SlideModel>();
imageList.add(new SlideModel("url", "title"));
imageList.add(new SlideModel("url));
imageList.add(new SlideModel("url", "title"));

imageSlider.setImageList(imageList);
```

```Xml
<com.denzcoskun.imageslider.ImageSlider
        android:id="@+id/image_slider"
        android:layout_width="wrap_content"
        android:layout_height="300dp"
        app:auto_cycle="true"
        app:corner_radius="20"
        app:period="1000"
        app:delay="0"/>
```

**Comment by chigup** [comment]
i have tried it but it is showing C:\Users\f2016\.gradle\caches\transforms-2\files-2.1\3632b6b98768d88360b612f5cd2ddb6e\jetified-ImageSlideshow-0.0.6\res\values\values.xml:3:5-12:25: AAPT: error: resource previously defined here. 
How to solve it
