### ISSUE TITLE
Making indicator invisible programmatically?

### ISSUE THREAD

**Issue by buckydroid** [denzcoskun/ImageSlideshow#73]
I want to make the indicator invisible or set an invisible drawable as indicator when there's only one image.

I know we can do that in XML, 

```
app:iss_selected_dot="@drawable/default_selected_dot"
app:iss_unselected_dot="@drawable/default_unselected_dot"
```

But is there any way to do that programmatically?

**Comment by denzcoskun** [comment]
app:iss_no_dots="true"   with version 0.1.2
