### ISSUE TITLE
Your project has set `android.useAndroidX=true`, but configuration `:app:debugRuntimeClasspath` still contains legacy support libraries

### ISSUE THREAD

**Issue by Takshaksh** [denzcoskun/ImageSlideshow#75]
I am getting the following warning in the project while building it in the Android Studio. How this can be resolved properly or the library needs to upgrade itself. Anyone, please clarify.

`Your project has set `android.useAndroidX=true`, but configuration `:app:debugRuntimeClasspath` still contains legacy support libraries, which may cause runtime issues.
This behavior will not be allowed in Android Gradle plugin 8.0.
Please use only AndroidX dependencies or set `android.enableJetifier=true` in the `gradle.properties` file to migrate your project to AndroidX (see https://developer.android.com/jetpack/androidx/migrate for more info).
The following legacy support libraries are detected:
:app:debugRuntimeClasspath -> com.github.denzcoskun:ImageSlideshow:0.1.0 -> com.squareup.picasso:picasso:2.71828 -> com.android.support:support-annotations:27.1.0
:app:debugRuntimeClasspath -> com.github.denzcoskun:ImageSlideshow:0.1.0 -> com.squareup.picasso:picasso:2.71828 -> com.android.support:exifinterface:27.1.0
`

**Comment by ryuuudev** [comment]
basically, you need to put `android.enableJetifier=true` in `gradle.properties`
