### ISSUE TITLE
Smooth changes

### ISSUE THREAD

**Issue by jonrysimbolon** [denzcoskun/ImageSlideshow#77]
how to make change from one picture to other more smoothly than before ?

**Comment by cz9dev** [comment]
In my opinion, you should work with the app:iss_period and app:iss_delay parameters, increasing or decreasing them

**Comment by faizy313786** [comment]
Which one is the best smooth value if you dont mind please suggest one

**Comment by denzcoskun** [comment]
You can try new version 0.1.2 with animations.
