### ISSUE TITLE
Problem with RecyclerView

### ISSUE THREAD

**Issue by amebrahimi** [denzcoskun/ImageSlideshow#8]
Hello and thanks for this library. I have a problem with ImageSlider in a RecyclerView. The problem is when I put it in a RecyclerView when I scroll down and up when the view is being created for the second time, sometimes the timer will go dumb and starts changing the image fast like at 700 ms pace and it doesn't obey the "period" and "delay" that is given anymore.

**Comment by denzcoskun** [comment]
Hello, this library doesn't designed using in RecyclerView. If use in RecyclerView, it can be not to work well because every image slider has a cycle thread. You should use it without auto cycle in RecyclerView for I didn't add thread controller.

**Comment by amebrahimi** [comment]
Is there any condition you could think of that I could put in my code to work with RecyclerView, because I need it, and thank you for replying.

**Comment by denzcoskun** [comment]
Hello again,
I added a slide controller. It maybe can solve your problem. You can use it with new version.

```kt
imageSlider.startSliding(3000) // with new period
imageSlider.startSliding()
imageSlider.stopSliding()
```
```kt
implementation 'com.github.denzcoskun:ImageSlideshow:0.0.6'
```

**Comment by amebrahimi** [comment]
Well, thank you I will try it.
