### ISSUE TITLE
How to set scaleType for Image?

### ISSUE THREAD

**Issue by pelaio** [denzcoskun/ImageSlideshow#9]

**Comment by haiderwaseem-programmer** [comment]
I just cannot change its scale type ...?? waiting for ur response bro

**Comment by denzcoskun** [comment]
You can use only center crop.  Add true if you want to use it.
```
imageList.add(SlideModel("String Url" or R.drawable, "title", true) // true = centerCrop for this image
imageSlider.setImageList(imageList, true) // true = centerCrop for all images
```

**Comment by haiderwaseem-programmer** [comment]
can u plz add scaleType 'Center' , or just remove the scale type which i guess by default is fitXY

**Comment by Ashwani10101** [comment]
@denzcoskun Bro Please Add other scale Types, Like Center Inside or atleast Remove FitXY, Images are out of proportions they look ugly
![Screenshot_2020-05-04-01-22-59-269_com example imagepreivewcollection](https://user-images.githubusercontent.com/54770264/80924341-ff442e00-8da5-11ea-9f08-d5df7bd503c3.jpg)
![Screenshot_2020-05-04-01-23-27-945_com example imagepreivewcollection](https://user-images.githubusercontent.com/54770264/80924344-010df180-8da6-11ea-8ca7-533c14b2b437.jpg)

**Comment by Ashwani10101** [comment]
@haiderwaseem-programmer Bro can you help me on this, How you fix your problem, which Library you used

**Comment by denzcoskun** [comment]
Hi, you can with new version.

implementation 'com.github.denzcoskun:ImageSlideshow:0.0.7'

Please read the readme before use. Scale types changed.
